<?php

namespace App\Models;

use App\BaseModel;
use App\User;

class Photo extends BaseModel
{
    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->status = 1;
        }); // TODO: Change the autogenerated stub
    }

    public function category()
    {
        return $this->belongsTo(Categories::class, 'category_id');
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updatedBy()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }
}
